version: '3'
services:
  app:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
  broker:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: broker
    ports:
      - "5672:5672" 
      - "15672:15672"
    volumes:
      - "./volume/rabbitmq-data:/var/lib/rabbitmq" 
    environment:
      RABBITMQ_DEFAULT_USER: "user" 
      RABBITMQ_DEFAULT_PASS: "password"